(function initDG(){
    if(!window.DG || !window.DG.FB){ setTimeout(initDG, 50); return; }
    var D=window.DG, FB=D.FB, ST=D.STATE;
    
    D.el=function(id){return document.getElementById(id)};
    D.qs=function(s,p){return(p||document).querySelector(s)};
    D.qsa=function(s,p){return(p||document).querySelectorAll(s)};
    
    D.showToast=function(m,t){t=t||'info';var c=D.el('toastContainer')||(function(){var x=document.createElement('div');x.id='toastContainer';x.className='toast-container';document.body.appendChild(x);return x})();var z=document.createElement('div');z.className='toast '+t;z.textContent=m;c.appendChild(z);setTimeout(function(){z.style.opacity='0';z.style.transform='translateX(50px)';z.style.transition='all 180ms';setTimeout(function(){z.remove()},180)},2600)};
    D.searchGoogle=function(q){if(!q.trim())return;window.open('https://www.google.com/search?q='+encodeURIComponent(q),'_blank')};
    D.showLoading=function(){var b=D.el('loadingBar');if(b){b.classList.add('active');b.classList.remove('done')}};
    D.hideLoading=function(){var b=D.el('loadingBar');if(b){b.classList.remove('active');b.classList.add('done');setTimeout(function(){b.classList.remove('done')},400)}};
    D.toggleDropdown=function(id){var m=D.el(id);if(m)m.classList.toggle('show')};
    D.openModal=function(id){var m=D.el(id);if(m)m.classList.add('show');var a=D.el('avatarMenu');if(a)a.classList.remove('show')};
    D.closeModal=function(id){var m=D.el(id);if(m)m.classList.remove('show')};
    D.openAddWidgetModal=function(){D.openModal('addWidgetModal')};
    D.openProfileModal=function(){D.openModal('profileModal')};
    D.openBackgroundModal=function(){D.openModal('pageSettingsModal');setTimeout(function(){var t=D.qs('[data-tab="tab-background"]');if(t)D.switchSettingsTab('tab-background',t)},80)};
    D.openPageSettingsModal=function(){D.openModal('pageSettingsModal');D._renderPageSettings()};

    // ===== LIGHTBOX =====
    D.openLightbox=function(url){ST.lightboxImg=url;D.el('lightboxImg').src=url;D.el('lightbox').classList.add('show')};
    D.closeLightbox=function(){D.el('lightbox').classList.remove('show');ST.lightboxImg=null};
    D.downloadImage=function(){if(!ST.lightboxImg)return;var a=document.createElement('a');a.href=ST.lightboxImg;a.download='dockgrid-image';a.click()};
    D.openImageNewTab=function(){if(ST.lightboxImg)window.open(ST.lightboxImg,'_blank')};

    // ===== PAGE TITLE =====
    D.savePageTitle=function(t){t=(t||'').trim()||'DockGrid Page';ST.currentPageTitle=t;var d=D.el('pageTitleDisplay');if(d)d.textContent=t;D._saveSetting('pageTitle',t)};

    // ===== PAGE SETTINGS =====
    D._renderPageSettings=function(){
        var tabs=[{id:'tab-general',label:'📄 General'},{id:'tab-background',label:'🖼 Background'},{id:'tab-layout',label:'📐 Layout'},{id:'tab-preferences',label:'🔍 Preferences'},{id:'tab-overview',label:'📊 Overview'},{id:'tab-analytics',label:'📈 Analytics'}];
        D.el('settingsTabs').innerHTML=tabs.map(function(t,i){return'<button class="modal-tab'+(i===0?' active':'')+'" data-tab="'+t.id+'" onclick="DG.switchSettingsTab(\''+t.id+'\',this)">'+t.label+'</button>'}).join('');
        D.el('settingsTabContent').innerHTML=[
            '<div class="tab-content active" id="tab-general"><div class="form-group"><label class="form-label form-label-row">Page Title <small id="titleCount">0/50</small></label><input type="text" class="form-input" id="pageTitle" placeholder="Enter title" maxlength="50" oninput="document.getElementById(\'titleCount\').textContent=this.value.length+\'/50\'" value="'+(ST.currentPageTitle||'')+'"></div><div class="form-group"><label class="form-label">Description <small>(250 chars)</small></label><textarea class="form-input form-textarea" id="pageDescription" maxlength="250">'+(ST.settings.description||'')+'</textarea></div><div class="form-toggle"><span class="form-toggle-label">Auto Generate Description</span><label class="form-toggle-switch"><input type="checkbox"><span class="form-toggle-slider"></span></label></div><div class="form-group"><label class="form-label">Category</label><select class="form-select"><option>Personal</option><option>Work</option><option>School</option><option>Projects</option></select></div><div class="form-group"><label class="form-label">Icon</label><input type="text" class="form-input" value="📄"></div><div class="form-toggle"><span class="form-toggle-label">Hide Page (archive)</span><label class="form-toggle-switch"><input type="checkbox"><span class="form-toggle-slider"></span></label></div><div style="display:flex;gap:6px;margin-top:8px"><button class="btn btn-light btn-sm" style="flex:1;justify-content:center">📋 Duplicate</button><button class="btn btn-light btn-sm" style="flex:1;justify-content:center;color:#f87171">🗑 Delete</button></div></div>',
            '<div class="tab-content" id="tab-background"><div class="form-group"><label class="form-label">Background Type</label><select class="form-select"><option>Image</option><option>Solid Color</option><option>Gradient</option></select></div><div class="form-group"><label class="form-label">Select Image</label><div class="image-grid" id="bgImageGrid"></div></div><div class="form-group"><label class="form-label">Upload Image</label><input type="file" class="form-input" id="bgUpload" accept="image/*" onchange="DG.uploadBg(event)" style="padding:6px"></div><div class="form-group"><label class="form-label">Widget Transparency: <span id="opLabel">96%</span></label><input type="range" class="form-range" min="70" max="100" value="96" id="widgetOpacity" oninput="DG.updateOpacity(this.value)"></div><button class="btn btn-light" style="width:100%;justify-content:center;margin-top:6px" onclick="DG.resetBg()">Reset Background</button></div>',
            '<div class="tab-content" id="tab-layout"><div class="form-group"><label class="form-label">Grid Columns</label><input type="number" class="form-input" min="1" max="4" value="'+(ST.colCount||3)+'" onchange="DG.updateCols(this.value)"></div><div class="form-group"><label class="form-label">Widget Gap: <span id="gapLabel">10px</span></label><input type="range" class="form-range" min="4" max="30" value="10" oninput="document.getElementById(\'gapLabel\').textContent=this.value+\'px\'"></div><div class="form-toggle"><span class="form-toggle-label">Auto Arrange</span><label class="form-toggle-switch"><input type="checkbox"><span class="form-toggle-slider"></span></label></div><div class="form-toggle"><span class="form-toggle-label">Lock Layout</span><label class="form-toggle-switch"><input type="checkbox"><span class="form-toggle-slider"></span></label></div><button class="btn btn-light" style="width:100%;justify-content:center;margin-top:6px">Reset Layout</button></div>',
            '<div class="tab-content" id="tab-preferences"><div class="form-toggle"><span class="form-toggle-label">Show Search Bar</span><label class="form-toggle-switch"><input type="checkbox" checked><span class="form-toggle-slider"></span></label></div><div class="form-group"><label class="form-label">Search Engine</label><select class="form-select"><option>Google</option><option>DuckDuckGo</option><option>Bing</option></select></div><div class="form-group"><label class="form-label">Open Links</label><select class="form-select" id="linkTarget"><option value="_blank">New Tab</option><option value="_self">Same Tab</option></select></div><div class="form-toggle"><span class="form-toggle-label">Show Widget Headers</span><label class="form-toggle-switch"><input type="checkbox" checked><span class="form-toggle-slider"></span></label></div><div class="form-toggle"><span class="form-toggle-label">Confirm Before Deleting</span><label class="form-toggle-switch"><input type="checkbox" checked><span class="form-toggle-slider"></span></label></div></div>',
            '<div class="tab-content" id="tab-overview"><p style="color:#999;font-size:9px;margin-bottom:10px">Read-only — updates automatically.</p><div class="stats-grid">'+['Total Widgets','Bookmarks','Tasks','Completed','Notes','RSS Feeds','Projects','Images'].map(function(l,i){var v=[ST.pageStats.totalWidgets,ST.pageStats.totalBookmarks,ST.pageStats.totalTasks,ST.pageStats.completedTasks,ST.pageStats.totalNotes,ST.pageStats.totalFeeds,ST.pageStats.totalProjects,ST.pageStats.totalImages][i]||0;return'<div class="stat-card"><div class="stat-card-value">'+v+'</div><div class="stat-card-label">'+l+'</div></div>'}).join('')+'</div></div>',
            '<div class="tab-content" id="tab-analytics"><div style="text-align:center;padding:24px;color:#bbb"><iconify-icon icon="mdi:chart-bar" width="32" height="32" style="opacity:0.25"></iconify-icon><p style="margin-top:6px;font-size:10px">Analytics are disabled.</p><p style="font-size:9px;margin-top:2px">Enable to collect anonymous usage statistics.</p></div></div>'
        ].join('');
        D._setupBgGrid();
    };
    
    D.switchSettingsTab=function(tid,btn){D.qsa('.modal-tab').forEach(function(t){t.classList.remove('active')});D.qsa('.tab-content').forEach(function(t){t.classList.remove('active')});if(btn)btn.classList.add('active');var t=D.el(tid);if(t)t.classList.add('active')};

    // ===== PAGES =====
    D.openPagesSidebar=function(){D.el('pagesSidebar').classList.add('open');D.el('pagesOverlay').classList.add('show');D.el('avatarMenu').classList.remove('show')};
    D.closePagesSidebar=function(){D.el('pagesSidebar').classList.remove('open');D.el('pagesOverlay').classList.remove('show')};
    D.createNewPage=async function(){if(!ST.currentUser)return;var q=FB.query(FB.collection(FB.db,FB.COL.PAGES),FB.where('userId','==',ST.currentUser.uid));var s=await FB.getDocs(q);if(s.size>=3){D.showToast('Max 3 pages','error');return}var id='page_'+Date.now();await FB.setDoc(FB.doc(FB.db,FB.COL.PAGES,id),{id:id,userId:ST.currentUser.uid,title:'New Page',icon:'📄',order:s.size,createdAt:FB.serverTimestamp(),updatedAt:FB.serverTimestamp()});D.showToast('Page created!','success')};
    D.switchPage=function(id){ST.currentPageId=id;D.closePagesSidebar();D.showToast('Switched','success')};
    D.renderPagesList=function(p){var l=D.el('pagesList');if(!l)return;if(!p.length){l.innerHTML='<div class="pages-empty">No pages yet</div>'}else{l.innerHTML=p.map(function(x){var a=x.id===ST.currentPageId?' active':'';var lb=x.id===ST.currentPageId?' (current)':'';return'<div class="page-item'+a+'" onclick="DG.switchPage(\''+x.id+'\')"><iconify-icon icon="mdi:file-document-outline" width="13" height="13"></iconify-icon>'+(x.title||'Untitled')+lb+'</div>'}).join('')}var lim=D.el('pageLimit');if(lim)lim.textContent=p.length+'/3 used';var b=D.el('newPageBtn');if(b){b.disabled=p.length>=3;b.style.opacity=p.length>=3?'0.5':'1'}};

    // ===== BACKGROUND =====
    D._setupBgGrid=function(){var g=D.el('bgImageGrid');if(g)g.innerHTML=FB.DEFAULT_BGS.map(function(u){return'<div class="image-option" style="background-image:url(\''+u+'\')" onclick="DG.setBg(\''+u+'\')" data-bg="'+u+'"></div>'}).join('')};
    D.setBg=function(url){ST.currentBg=url;D._updateBgDisplay(url);D._saveSetting('bg',url)};
    D._updateBgDisplay=function(url){var l=D.el('bgLayer');if(l)l.style.backgroundImage='url('+url+')';D.qsa('.image-option').forEach(function(e){e.classList.remove('selected');if(e.dataset.bg===url)e.classList.add('selected')})};
    D.resetBg=function(){D.setBg(FB.DEFAULT_BGS[0]);D.showToast('Background reset','success')};
    D.uploadBg=async function(e){var f=e.target.files[0];if(!f)return;D.showLoading();var fd=new FormData();fd.append('image',f);try{var r=await fetch('https://api.imgbb.com/1/upload?key='+FB.IMGBB_KEY,{method:'POST',body:fd});var d=await r.json();if(d.success){D.setBg(d.data.url);D.showToast('Background updated!','success')}}catch(ex){}D.hideLoading()};
    D.uploadProfile=async function(e){var f=e.target.files[0];if(!f)return;D.showLoading();var fd=new FormData();fd.append('image',f);try{var r=await fetch('https://api.imgbb.com/1/upload?key='+FB.IMGBB_KEY,{method:'POST',body:fd});var d=await r.json();if(d.success){D._updateProfileImages(d.data.url);D._saveSetting('profileImg',d.data.url);D.closeModal('profileModal');D.showToast('Updated!','success')}}catch(ex){}D.hideLoading()};
    D._updateProfileImages=function(url){var a=D.el('avatarBtn'),p=D.el('profileAvatar');if(a)a.innerHTML='<img src="'+url+'" alt="P">';if(p)p.innerHTML='<img src="'+url+'" alt="P" style="width:100%;height:100%;object-fit:cover;border-radius:50%">'};

    // ===== SETTINGS =====
    D._saveSetting=async function(k,v){if(!ST.currentUser)return;await FB.setDoc(FB.doc(FB.db,FB.COL.SETTINGS,ST.currentUser.uid),{[k]:v},{merge:true})};
    D.updateOpacity=function(v){ST.widgetOpacity=parseInt(v);var o=D.el('opLabel');if(o)o.textContent=v+'%';D._updateOpacityUI(v);D._saveSetting('opacity',parseInt(v))};
    D._updateOpacityUI=function(v){var o=v/100;D.qsa('.widget').forEach(function(w){w.style.background='rgba(255,255,255,'+o+')';var h=w.querySelector('.widget-header');if(h)h.style.background='rgba(250,251,252,'+o+')'})};
    D.updateCols=function(v){ST.colCount=parseInt(v);D._updateColDisplay(v);D._saveSetting('cols',parseInt(v))};
    D._updateColDisplay=function(v){var g=D.el('widgetGrid');if(!g)return;g.className='widget-grid';if(v>=1&&v<=4)g.classList.add('cols-'+v);D._initMasonry()};

    // ===== WIDGETS =====
    D.addWidget=async function(type){var names={bookmarks:'Bookmarks',rss:'RSS News',notes:'Notes',tasks:'Tasks',embed:'Embed',project:'Project',clock:'Clock',gallery:'Gallery',calculator:'Calculator'};var sizes={bookmarks:'medium',rss:'medium',notes:'small',tasks:'medium',embed:'large',project:'large',clock:'small',gallery:'large',calculator:'small'};var id=type+'_'+Date.now();D.showLoading();await FB.setDoc(FB.doc(FB.db,FB.COL.WIDGETS,id),{id:id,type:type,title:names[type]||'Widget',size:sizes[type]||'medium',userId:ST.currentUser.uid,pageId:ST.currentPageId||'default',data:{bookmarks:[],tasks:[],content:'',images:[],projectWidgets:[],embedUrl:'',rssUrl:''},createdAt:FB.serverTimestamp(),updatedAt:FB.serverTimestamp()});D.closeModal('addWidgetModal');D.showToast('Added '+names[type],'success');D.hideLoading()};
    D.removeWidget=async function(id){if(!confirm('Remove?'))return;await FB.deleteDoc(FB.doc(FB.db,FB.COL.WIDGETS,id));D.closeContextMenu();D.showToast('Removed','success')};
    D.changeWidgetSize=async function(id,size){await FB.setDoc(FB.doc(FB.db,FB.COL.WIDGETS,id),{size:size},{merge:true});D.closeContextMenu();D.showToast('Size updated','success')};

    // ===== CONTEXT MENU =====
    D.openContextMenu=function(wid,e){e.stopPropagation();e.preventDefault();var m=D.el('widgetContextMenu');if(!m)return;var w=ST.widgetsData.find(function(x){return x.id===wid});if(!w)return;var items=D._menuItems(w);m.innerHTML=items.map(function(x){if(x.label==='divider')return'<div class="dropdown-divider"></div>';return'<button class="dropdown-item'+(x.danger?' danger':'')+'" onclick="DG.closeContextMenu();'+x.action+'"><iconify-icon icon="'+x.icon+'" width="13" height="13"></iconify-icon>'+x.label+'</button>'}).join('');var x=e.clientX,y=e.clientY;if(x+180>window.innerWidth)x=window.innerWidth-190;if(y+280>window.innerHeight)y=window.innerHeight-290;m.style.left=x+'px';m.style.top=y+'px';m.classList.add('show')};
    D.closeContextMenu=function(){var m=D.el('widgetContextMenu');if(m)m.classList.remove('show')};
    D._menuItems=function(w){var id=w.id;var sizes=[{label:'Small',icon:'mdi:resize',action:'DG.changeWidgetSize(\''+id+'\',\'small\')'},{label:'Medium',icon:'mdi:resize',action:'DG.changeWidgetSize(\''+id+'\',\'medium\')'},{label:'Large',icon:'mdi:resize',action:'DG.changeWidgetSize(\''+id+'\',\'large\')'},{label:'Huge',icon:'mdi:resize',action:'DG.changeWidgetSize(\''+id+'\',\'huge\')'}];var c=[{label:'Edit',icon:'mdi:pencil-outline',action:'DG.openEditPanel(\''+id+'\')'},{label:'divider'}].concat(sizes).concat([{label:'divider'},{label:'Delete',icon:'mdi:delete-outline',action:'DG.removeWidget(\''+id+'\')',danger:true}]);var bt={bookmarks:[{label:'Open all',icon:'mdi:open-in-new',action:'DG._openAllBm(\''+id+'\')'},{label:'Add',icon:'mdi:bookmark-plus-outline',action:'DG.openEditPanel(\''+id+'\')'},{label:'divider'}].concat(c),notes:[{label:'Edit',icon:'mdi:note-edit-outline',action:'DG.openEditPanel(\''+id+'\')'},{label:'divider'}].concat(c),tasks:[{label:'Add task',icon:'mdi:playlist-plus',action:'DG.openEditPanel(\''+id+'\')'},{label:'divider'}].concat(c),project:[{label:'Edit',icon:'mdi:folder-edit-outline',action:'DG.openEditPanel(\''+id+'\')'},{label:'divider'}].concat(c)};return bt[w.type]||c};
    D._openAllBm=function(id){var w=ST.widgetsData.find(function(x){return x.id===id});if(w&&w.data&&w.data.bookmarks){w.data.bookmarks.forEach(function(b){window.open(b.url,'_blank')});D.showToast('Opened '+w.data.bookmarks.length+' links','success')}};

    // ===== EDIT PANEL =====
    D.openEditPanel=function(wid){var w=ST.widgetsData.find(function(x){return x.id===wid});if(!w)return;ST.editingWidgetId=wid;D.el('editPanelTitle').textContent='Edit '+(w.title||'Widget');var b=D.el('editPanelBody');
        switch(w.type){
            case'bookmarks':b.innerHTML='<div class="form-group"><label class="form-label">Add URL</label><input type="url" class="form-input" id="editBmUrl" placeholder="https://..."></div><button class="btn btn-primary btn-sm" style="width:100%;margin-bottom:8px" onclick="DG._addBmPanel()">Add</button><div class="edit-list" id="editBmList"></div>';D._renderEditBm(w);break;
            case'notes':b.innerHTML='<div class="form-group"><label class="form-label">Content</label><textarea class="form-input form-textarea" id="editNoteContent" style="min-height:180px;font-size:12px">'+((w.data&&w.data.content)||'')+'</textarea></div>';break;
            case'tasks':b.innerHTML='<div class="form-group"><label class="form-label">New Task</label><input type="text" class="form-input" id="editTaskInput" placeholder="Task..."><button class="btn btn-primary btn-sm" style="width:100%;margin-top:5px" onclick="DG._addTaskPanel()">Add</button></div><div class="edit-list" id="editTaskList"></div>';D._renderEditTasks(w);break;
            case'embed':b.innerHTML='<div class="form-group"><label class="form-label">URL</label><input type="url" class="form-input" id="editEmbedUrl" placeholder="YouTube, Figma..."></div>';break;
            case'rss':b.innerHTML='<div class="form-group"><label class="form-label">RSS URL</label><input type="url" class="form-input" id="editRssUrl" placeholder="https://feeds..."></div>';break;
            case'project':b.innerHTML='<div class="form-group"><label class="form-label">Name</label><input type="text" class="form-input" id="editProjectName"><label class="form-label" style="margin-top:8px">Description</label><textarea class="form-input form-textarea" id="editProjectDesc"></textarea><label class="form-label" style="margin-top:8px">GitHub</label><input type="url" class="form-input" id="editProjectUrl"><label class="form-label" style="margin-top:8px">Website</label><input type="url" class="form-input" id="editProjectWebsite"><label class="form-label" style="margin-top:8px">Add Resources</label><div class="widget-type-grid" style="grid-template-columns:repeat(2,1fr)">'+[{t:'bookmarks',i:'mdi:bookmark-multiple-outline',n:'Bookmarks'},{t:'rss',i:'mdi:rss',n:'RSS'},{t:'gallery',i:'mdi:image-multiple-outline',n:'Gallery'},{t:'notes',i:'mdi:note-text-outline',n:'Note'},{t:'tasks',i:'mdi:checkbox-marked-outline',n:'Tasks'},{t:'embed',i:'mdi:code-tags',n:'Embed'}].map(function(s){return'<button class="widget-type-btn" onclick="DG._addProjectSub(\''+wid+'\',\''+s.t+'\')"><iconify-icon icon="'+s.i+'"></iconify-icon>'+s.n+'</button>'}).join('')+'</div>';break;
            case'clock':b.innerHTML='<div class="form-group"><label class="form-label">Format</label><select class="form-select"><option>12-hour</option><option>24-hour</option></select></div>';break;
            case'gallery':b.innerHTML='<div class="form-group"><label class="form-label">Upload</label><input type="file" class="form-input" accept="image/*" multiple onchange="DG._uploadGallery(event)"></div><div id="editGalleryPreview" class="gallery-masonry"></div>';break;
            case'calculator':b.innerHTML='<div class="form-group"><label class="form-label">Mode</label><select class="form-select"><option>Basic</option><option>Scientific</option></select></div>';break;
        }
        D.el('editPanel').classList.add('open');D.el('editPanelOverlay').classList.add('show');D.closeContextMenu();
    };
    D.closeEditPanel=function(){D.el('editPanel').classList.remove('open');D.el('editPanelOverlay').classList.remove('show');ST.editingWidgetId=null};
    D.saveEditPanel=async function(){var wid=ST.editingWidgetId;if(!wid)return;var w=ST.widgetsData.find(function(x){return x.id===wid});if(!w)return;
        switch(w.type){case'notes':var c=D.el('editNoteContent');if(c)await FB.setDoc(FB.doc(FB.db,FB.COL.WIDGETS,wid),{data:{content:c.value},updatedAt:FB.serverTimestamp()},{merge:true});break;
            case'embed':var u=D.el('editEmbedUrl');if(u)await FB.setDoc(FB.doc(FB.db,FB.COL.WIDGETS,wid),{data:{embedUrl:u.value},updatedAt:FB.serverTimestamp()},{merge:true});break;
            case'rss':var r=D.el('editRssUrl');if(r)await FB.setDoc(FB.doc(FB.db,FB.COL.WIDGETS,wid),{data:{rssUrl:r.value},updatedAt:FB.serverTimestamp()},{merge:true});break;
            case'project':var pn=D.el('editProjectName'),pd=D.el('editProjectDesc'),pu=D.el('editProjectUrl'),pw=D.el('editProjectWebsite');var pd={};if(pn)pd.name=pn.value;if(pd)pd.description=pd.value;if(pu)pd.githubUrl=pu.value;if(pw)pd.website=pw.value;await FB.setDoc(FB.doc(FB.db,FB.COL.WIDGETS,wid),{data:Object.assign({},w.data||{},pd),updatedAt:FB.serverTimestamp()},{merge:true});break;
        }D.closeEditPanel();D.showToast('Saved','success')};
    
    D._addBmPanel=async function(){var u=(D.el('editBmUrl').value||'').trim();if(!u)return;D.el('editBmUrl').value='';try{var hn=new URL(u).hostname;var fv='https://www.google.com/s2/favicons?domain='+hn+'&sz=64';var tl=hn;try{var r=await fetch('https://api.microlink.io/?url='+encodeURIComponent(u));var d=await r.json();if(d.status==='success'&&d.data.title)tl=d.data.title}catch(e){}var ref=FB.doc(FB.db,FB.COL.WIDGETS,ST.editingWidgetId);var s=await FB.getDoc(ref);if(s.exists()){var w=s.data();var bm=(w.data&&w.data.bookmarks)||[];bm.push({url:u,title:tl,favicon:fv,hostname:hn});await FB.setDoc(ref,{data:Object.assign({},w.data,{bookmarks:bm}),updatedAt:FB.serverTimestamp()},{merge:true});D._renderEditBm({data:{bookmarks:bm}})}}catch(e){D.showToast('Failed','error')}};
    D._renderEditBm=function(w){var l=D.el('editBmList');if(!l)return;var bm=(w.data&&w.data.bookmarks)||[];l.innerHTML=bm.map(function(b,i){return'<div class="edit-item"><img src="'+b.favicon+'" style="width:12px;height:12px"><span>'+b.title+'</span><button class="btn-x" onclick="DG._removeEditBm('+i+')">✕</button></div>'}).join('')};
    D._removeEditBm=async function(i){var ref=FB.doc(FB.db,FB.COL.WIDGETS,ST.editingWidgetId);var s=await FB.getDoc(ref);if(s.exists()){var w=s.data();var bm=(w.data&&w.data.bookmarks)||[];bm.splice(i,1);await FB.setDoc(ref,{data:Object.assign({},w.data,{bookmarks:bm}),updatedAt:FB.serverTimestamp()},{merge:true});D._renderEditBm({data:{bookmarks:bm}})}};
    D._addTaskPanel=async function(){var t=D.el('editTaskInput');if(!t||!t.value.trim())return;var tx=t.value.trim();t.value='';var ref=FB.doc(FB.db,FB.COL.WIDGETS,ST.editingWidgetId);var s=await FB.getDoc(ref);if(s.exists()){var w=s.data();var ts=(w.data&&w.data.tasks)||[];ts.push({text:tx,done:false});await FB.setDoc(ref,{data:Object.assign({},w.data,{tasks:ts}),updatedAt:FB.serverTimestamp()},{merge:true});D._renderEditTasks({data:{tasks:ts}})}};
    D._renderEditTasks=function(w){var l=D.el('editTaskList');if(!l)return;var ts=(w.data&&w.data.tasks)||[];l.innerHTML=ts.map(function(t,i){return'<div class="edit-item" onclick="DG._toggleEditTask('+i+')"><iconify-icon icon="'+(t.done?'mdi:checkbox-marked':'mdi:checkbox-blank-outline')+'" width="13" height="13" style="color:'+(t.done?'var(--green-500)':'#ccc')+'"></iconify-icon><span style="text-decoration:'+(t.done?'line-through':'none')+'">'+t.text+'</span></div>'}).join('')};
    D._toggleEditTask=async function(i){var ref=FB.doc(FB.db,FB.COL.WIDGETS,ST.editingWidgetId);var s=await FB.getDoc(ref);if(s.exists()){var w=s.data();var ts=(w.data&&w.data.tasks)||[];if(ts[i]){ts[i].done=!ts[i].done;await FB.setDoc(ref,{data:Object.assign({},w.data,{tasks:ts}),updatedAt:FB.serverTimestamp()},{merge:true});D._renderEditTasks({data:{tasks:ts}})}}};
    D._uploadGallery=async function(e){var fs=e.target.files;if(!fs.length)return;var ref=FB.doc(FB.db,FB.COL.WIDGETS,ST.editingWidgetId);var s=await FB.getDoc(ref);var imgs=(s.exists()&&s.data().data&&s.data().data.images)||[];for(var i=0;i<fs.length;i++){var fd=new FormData();fd.append('image',fs[i]);try{var r=await fetch('https://api.imgbb.com/1/upload?key='+FB.IMGBB_KEY,{method:'POST',body:fd});var d=await r.json();if(d.success)imgs.push(d.data.url)}catch(ex){}}await FB.setDoc(ref,{data:Object.assign({},s.exists()?s.data().data:{},{images:imgs}),updatedAt:FB.serverTimestamp()},{merge:true})};
    D._addProjectSub=async function(pid,type){var names={bookmarks:'Bookmarks',rss:'RSS',gallery:'Gallery',notes:'Note',tasks:'Tasks',embed:'Embed'};var ref=FB.doc(FB.db,FB.COL.WIDGETS,pid);var s=await FB.getDoc(ref);if(s.exists()){var w=s.data();var subs=(w.data&&w.data.projectWidgets)||[];subs.push({type:type,title:names[type]||'Widget',data:{}});await FB.setDoc(ref,{data:Object.assign({},w.data,{projectWidgets:subs}),updatedAt:FB.serverTimestamp()},{merge:true});D.showToast('Added','success')}};

    // ===== INLINE ACTIONS =====
    D.toggleTaskInline=async function(wid,i){var ref=FB.doc(FB.db,FB.COL.WIDGETS,wid);var s=await FB.getDoc(ref);if(s.exists()){var w=s.data();var ts=(w.data&&w.data.tasks)||[];if(ts[i]){ts[i].done=!ts[i].done;await FB.setDoc(ref,{data:Object.assign({},w.data,{tasks:ts}),updatedAt:FB.serverTimestamp()},{merge:true})}}};
    D.hideCompletedTasks=async function(id){var ref=FB.doc(FB.db,FB.COL.WIDGETS,id);var s=await FB.getDoc(ref);if(s.exists()){var w=s.data();var ts=(w.data&&w.data.tasks)||[];ts=ts.filter(function(t){return!t.done});await FB.setDoc(ref,{data:Object.assign({},w.data,{tasks:ts}),updatedAt:FB.serverTimestamp()},{merge:true});D.showToast('Cleared','success')}};
    D.updateNoteContent=async function(wid,content){var ref=FB.doc(FB.db,FB.COL.WIDGETS,wid);await FB.setDoc(ref,{data:{content:content},updatedAt:FB.serverTimestamp()},{merge:true})};
    D.saveNotesInline=function(wid,el){D.updateNoteContent(wid,el.innerText)};

    // ===== CLOCK =====
    D.startClock=function(wid){var u=function(){var el=document.getElementById('clock_'+wid);if(!el)return;var n=new Date();el.textContent=n.toLocaleTimeString();var de=document.getElementById('clockDate_'+wid);if(de)de.textContent=n.toLocaleDateString(undefined,{weekday:'short',month:'short',day:'numeric'});var le=document.getElementById('clockLoc_'+wid);if(le)le.textContent=Intl.DateTimeFormat().resolvedOptions().timeZone||'Local'};u();setInterval(u,1000)};

    // ===== CALCULATOR =====
    D.calcInput=function(wid,k){var i=document.getElementById('calcInput_'+wid);if(i)i.value+=k;var d=document.getElementById('calcDisplay_'+wid);if(d)d.textContent=i?i.value:'0'};
    D.calcResult=function(wid){var i=document.getElementById('calcInput_'+wid);var d=document.getElementById('calcDisplay_'+wid);if(!i)return;try{var r=Function('"use strict";return ('+i.value+')')();i.value=r;if(d)d.textContent=r}catch(e){if(d)d.textContent='Error';i.value=''}};
    D.calcClear=function(wid){var i=document.getElementById('calcInput_'+wid);var d=document.getElementById('calcDisplay_'+wid);if(i)i.value='';if(d)d.textContent='0'};

    // ===== RENDER WIDGET BODY =====
    D._renderWidgetBody=function(w){
        var b='';
        switch(w.type){
            case'bookmarks':var bm=(w.data&&w.data.bookmarks)||[];if(!bm.length)b='<div class="widget-empty"><iconify-icon icon="mdi:bookmark-multiple-outline" width="22" height="22"></iconify-icon><p>No bookmarks</p><button class="btn btn-primary btn-sm" onclick="DG.openEditPanel(\''+w.id+'\')">Add</button></div>';else b='<div class="bookmark-grid">'+bm.map(function(x){var n=x.title||x.hostname||'';if(n.length>7)n=n.substring(0,7)+'..';return'<a href="'+x.url+'" target="_blank" class="bookmark-card" rel="noopener" title="'+(x.title||'')+'"><img src="'+x.favicon+'" class="bookmark-card-icon" onerror="this.style.display=\'none\'"><span class="bookmark-card-name">'+n+'</span></a>'}).join('')+'</div>';break;
            case'notes':var c=(w.data&&w.data.content)||'';b='<div class="note-toolbar"><button title="Bold" onclick="document.execCommand(\'bold\')"><b>B</b></button><button title="Italic" onclick="document.execCommand(\'italic\')"><i>I</i></button><button title="Underline" onclick="document.execCommand(\'underline\')"><u>U</u></button><button title="List" onclick="document.execCommand(\'insertUnorderedList\')">≡</button><button title="Link" onclick="var u=prompt(\'URL:\');if(u)document.execCommand(\'createLink\',false,u)">🔗</button></div>';if(!c)b+='<div class="note-content" contenteditable="true" oninput="DG.saveNotesInline(\''+w.id+'\',this)" onblur="DG.saveNotesInline(\''+w.id+'\',this)"></div>';else b+='<div class="note-content" contenteditable="true" oninput="DG.saveNotesInline(\''+w.id+'\',this)" onblur="DG.saveNotesInline(\''+w.id+'\',this)">'+c+'</div>';break;
            case'tasks':var ts=(w.data&&w.data.tasks)||[];if(!ts.length)b='<div class="widget-empty"><iconify-icon icon="mdi:checkbox-marked-outline" width="22" height="22"></iconify-icon><p>No tasks</p><button class="btn btn-primary btn-sm" onclick="DG.openEditPanel(\''+w.id+'\')">Add</button></div>';else{var dn=ts.filter(function(t){return t.done}).length;var pct=Math.round(dn/ts.length*100);var ad=dn===ts.length;b='<div class="task-progress"><div class="task-progress-bar" style="width:'+pct+'%"></div></div><div class="task-stats"><span>'+dn+'/'+ts.length+' done</span><span>'+pct+'%</span></div>';b+=ts.map(function(t,i){return'<div class="task-item" onclick="DG.toggleTaskInline(\''+w.id+'\','+i+')"><iconify-icon icon="'+(t.done?'mdi:checkbox-marked':'mdi:checkbox-blank-outline')+'" width="14" height="14" style="color:'+(t.done?'var(--green-500)':'#ccc')+';flex-shrink:0"></iconify-icon><span style="text-decoration:'+(t.done?'line-through':'none')+';opacity:'+(t.done?'0.5':'1')+'">'+t.text+'</span></div>'}).join('');if(ad)b+='<div style="text-align:center;margin-top:6px"><button class="btn btn-primary btn-sm" onclick="DG.hideCompletedTasks(\''+w.id+'\')">✨ All done!</button></div>'}break;
            case'embed':var eu=(w.data&&w.data.embedUrl)||'';if(!eu)b='<div class="widget-empty"><iconify-icon icon="mdi:code-tags" width="22" height="22"></iconify-icon><p>No embed</p><button class="btn btn-primary btn-sm" onclick="DG.openEditPanel(\''+w.id+'\')">Add</button></div>';else{var et=D._detectEmbed(eu);if(et==='youtube'){var v=eu.match(/(?:v=|\/)([\w-]{11})/);v=v?v[1]:null;if(v)b='<div class="embed-preview"><iframe src="https://www.youtube.com/embed/'+v+'" allowfullscreen></iframe></div>'}else if(et==='vimeo'){var vm=eu.match(/vimeo\.com\/(\d+)/);vm=vm?vm[1]:null;if(vm)b='<div class="embed-preview"><iframe src="https://player.vimeo.com/video/'+vm+'" allowfullscreen></iframe></div>'}else b='<div class="embed-preview"><iframe src="'+eu+'" allowfullscreen></iframe></div>'}break;
            case'rss':b='<div class="widget-empty"><iconify-icon icon="mdi:rss" width="22" height="22"></iconify-icon><p>RSS Feed</p><button class="btn btn-primary btn-sm" onclick="DG.openEditPanel(\''+w.id+'\')">Add Feed</button></div>';break;
            case'project':var pd=w.data||{};var hasContent=pd.name||(pd.projectWidgets&&pd.projectWidgets.length);if(!hasContent)b='<div class="widget-empty"><iconify-icon icon="mdi:folder-outline" width="22" height="22"></iconify-icon><p>Setup project</p><button class="btn btn-primary btn-sm" onclick="DG.openEditPanel(\''+w.id+'\')">Setup</button></div>';else{b='<div class="project-card">';if(pd.name)b+='<div class="project-name">'+pd.name+'</div>';if(pd.description)b+='<div class="project-desc">'+pd.description+'</div>';b+='<div class="project-meta"><span><iconify-icon icon="mdi:account" width="11" height="11"></iconify-icon> Owner: You</span></div>';if(pd.githubUrl||pd.website)b+='<div class="project-links">'+(pd.website?'<a href="'+pd.website+'" target="_blank">🌐 Website</a>':'')+(pd.githubUrl?'<a href="'+pd.githubUrl+'" target="_blank">📂 GitHub</a>':'')+'</div>';var subs=pd.projectWidgets||[];if(subs.length){b+='<div class="project-resources">'+subs.map(function(s){var icons={bookmarks:'mdi:bookmark-multiple-outline',rss:'mdi:rss',gallery:'mdi:image-multiple-outline',notes:'mdi:note-text-outline',tasks:'mdi:checkbox-marked-outline',embed:'mdi:code-tags'};return'<span class="project-resource-tag"><iconify-icon icon="'+(icons[s.type]||'mdi:widget-outline')+'"></iconify-icon>'+(s.title||s.type)+'</span>'}).join('')+'</div>'}b+='</div>';if(subs.length){b+='<div style="margin-top:8px">';subs.forEach(function(s,i){b+='<div class="sub-widget"><div class="sub-widget-title">'+(s.title||s.type)+'</div>';if(s.type==='bookmarks'){var sbm=s.data&&s.data.bookmarks?s.data.bookmarks:[];b+=sbm.length?sbm.map(function(x){return'<a href="'+x.url+'" target="_blank" class="sub-widget-bookmark"><img src="'+x.favicon+'" style="width:12px;height:12px">'+x.title+'</a>'}).join(''):'<span style="color:#bbb;font-size:9px">No bookmarks</span>'}else if(s.type==='notes'){b+='<div class="sub-widget-note">'+(s.data&&s.data.content?s.data.content:'No notes')+'</div>'}else if(s.type==='tasks'){var sts=s.data&&s.data.tasks?s.data.tasks:[];b+=sts.map(function(t){return'<div class="sub-widget-task"><iconify-icon icon="'+(t.done?'mdi:checkbox-marked':'mdi:checkbox-blank-outline')+'" width="11" height="11" style="color:'+(t.done?'var(--green-500)':'#ccc')+'"></iconify-icon>'+t.text+'</div>'}).join('')}else{b+='<span style="color:#bbb;font-size:9px">'+s.type+' resource</span>'}b+='</div>'})}b+='</div>'}break;
            case'clock':b='<div class="clock-display"><div class="clock-time" id="clock_'+w.id+'">--:--:--</div><div class="clock-date" id="clockDate_'+w.id+'"></div><div class="clock-location" id="clockLoc_'+w.id+'">Local Time</div></div>';setTimeout(function(){D.startClock(w.id)},100);break;
            case'calculator':var ks=['C','÷','×','−','7','8','9','+','4','5','6','=','1','2','3','.','0','00',''];b='<div class="calc-display" id="calcDisplay_'+w.id+'">0</div><div class="calc-grid">'+ks.map(function(k){var a={'C':'C','÷':'/','×':'*','−':'-'};var v=a[k]||k;if(k==='C')return'<button class="calc-btn" onclick="DG.calcClear(\''+w.id+'\')" style="color:var(--red-500)">C</button>';if(k==='=')return'<button class="calc-btn equals" onclick="DG.calcResult(\''+w.id+'\')">=</button>';if('÷×−+'.indexOf(k)>=0)return'<button class="calc-btn operator" onclick="DG.calcInput(\''+w.id+'\',\''+v+'\')">'+k+'</button>';if(!k)return'<div></div>';return'<button class="calc-btn" onclick="DG.calcInput(\''+w.id+'\',\''+v+'\')">'+k+'</button>'}).join('')+'</div><input type="hidden" id="calcInput_'+w.id+'" value="">';break;
            case'gallery':var imgs=(w.data&&w.data.images)||[];if(!imgs.length)b='<div class="widget-empty"><iconify-icon icon="mdi:image-multiple-outline" width="22" height="22"></iconify-icon><p>No images</p><button class="btn btn-primary btn-sm" onclick="DG.openEditPanel(\''+w.id+'\')">Add</button></div>';else b='<div class="gallery-masonry">'+imgs.map(function(x){return'<div class="gallery-item" onclick="DG.openLightbox(\''+x+'\')"><img src="'+x+'" loading="lazy" onerror="this.parentElement.style.display=\'none\'"></div>'}).join('')+'</div>';break;
            default:b='<p style="color:#999;text-align:center;padding:14px">Widget ready</p>';
        }return b;
    };
    D._detectEmbed=function(u){try{var h=new URL(u).hostname;if(h.includes('youtube.com')||h.includes('youtu.be'))return'youtube';if(h.includes('vimeo.com'))return'vimeo';return'website'}catch(e){return'invalid'}};

    // ===== RENDER ALL + MASONRY =====
    D.renderWidgets=function(){var g=D.el('widgetGrid'),e=D.el('emptyState');if(!g)return;var wd=ST.widgetsData||[];if(!wd.length){g.innerHTML='';e.style.display='flex';if(g._masonry)try{g._masonry.destroy()}catch(ex){}g._masonry=null;return}e.style.display='none';
        g.innerHTML=wd.map(function(w){var sc=w.size?' size-'+w.size:'';return'<div class="widget'+sc+'" data-id="'+w.id+'"><div class="widget-header"><span class="widget-title" onclick="DG.openEditPanel(\''+w.id+'\')" title="Edit">'+(w.title||'Untitled')+'</span><div class="widget-hover-actions"><button class="widget-action-btn" onclick="DG.openEditPanel(\''+w.id+'\')"><iconify-icon icon="mdi:pencil-outline" width="13" height="13"></iconify-icon></button><button class="widget-menu-btn" onclick="DG.openContextMenu(\''+w.id+'\',event)"><iconify-icon icon="mdi:dots-horizontal" width="15" height="15"></iconify-icon></button></div></div><div class="widget-body">'+D._renderWidgetBody(w)+'</div></div>'}).join('');
        D._initMasonry();
    };
    D._initMasonry=function(){
        var g=D.el('widgetGrid');if(!g)return;
        if(g._masonry)try{g._masonry.destroy()}catch(ex){}
        if(typeof Masonry !== 'undefined'){
            var ms=new Masonry(g,{itemSelector:'.widget',columnWidth:'.widget',gutter:10,percentPosition:true,transitionDuration:'0.2s'});
            g._masonry=ms;
            if(typeof imagesLoaded !== 'undefined')imagesLoaded(g,function(){ms.layout()});
        }
    };

    // ===== INIT =====
    D.initApp=function(user){
        var nm=(user.displayName||(user.email?user.email.split('@')[0]:'user'));
        D.el('avatarInitial').textContent=nm[0].toUpperCase();D.el('profileInitial').textContent=nm[0].toUpperCase();
        D.el('usernameDisplay').textContent='@'+nm.toLowerCase().replace(/\s/g,'_');
        D._setupBgGrid();
        D.el('widgetTypeGrid').innerHTML=[{id:'bookmarks',icon:'mdi:bookmark-multiple-outline',name:'Bookmarks'},{id:'rss',icon:'mdi:rss',name:'RSS News'},{id:'notes',icon:'mdi:note-text-outline',name:'Notes'},{id:'tasks',icon:'mdi:checkbox-marked-outline',name:'Tasks'},{id:'embed',icon:'mdi:code-tags',name:'Embed'},{id:'project',icon:'mdi:folder-outline',name:'Project'},{id:'clock',icon:'mdi:clock-outline',name:'Clock'},{id:'gallery',icon:'mdi:image-multiple-outline',name:'Gallery'},{id:'calculator',icon:'mdi:calculator',name:'Calculator'}].map(function(t){return'<button class="widget-type-btn" onclick="DG.addWidget(\''+t.id+'\')"><iconify-icon icon="'+t.icon+'"></iconify-icon>'+t.name+'</button>'}).join('');
        D._loadSettings(user.uid);D._loadWidgets(user.uid);D._loadPages(user.uid);
    };
    D._loadSettings=async function(uid){try{var s=await FB.getDoc(FB.doc(FB.db,FB.COL.SETTINGS,uid));if(s.exists()){var d=s.data();if(d.bg){ST.currentBg=d.bg;D._updateBgDisplay(d.bg)}if(d.cols){ST.colCount=d.cols;D._updateColDisplay(d.cols)}if(d.opacity!=null){ST.widgetOpacity=d.opacity;D._updateOpacityUI(d.opacity)}if(d.pageTitle){ST.currentPageTitle=d.pageTitle;D.el('pageTitleDisplay').textContent=d.pageTitle}if(d.profileImg)D._updateProfileImages(d.profileImg);ST.settings=d}}catch(e){}};
    D._loadWidgets=function(uid){FB.onSnapshot(FB.collection(FB.db,FB.COL.WIDGETS),function(s){ST.widgetsData=[];var st={totalWidgets:0,totalBookmarks:0,totalTasks:0,completedTasks:0,totalNotes:0,totalFeeds:0,totalProjects:0,totalImages:0};s.forEach(function(d){if(d.data().userId===uid){var w={id:d.id,title:d.data().title,type:d.data().type,size:d.data().size,data:d.data().data};ST.widgetsData.push(w);st.totalWidgets++;if(w.type==='bookmarks')st.totalBookmarks+=(w.data&&w.data.bookmarks?w.data.bookmarks.length:0);if(w.type==='tasks'){var ts=w.data&&w.data.tasks?w.data.tasks:[];st.totalTasks+=ts.length;st.completedTasks+=ts.filter(function(t){return t.done}).length}if(w.type==='notes'&&w.data&&w.data.content)st.totalNotes++;if(w.type==='rss')st.totalFeeds++;if(w.type==='project')st.totalProjects++;if(w.type==='gallery')st.totalImages+=(w.data&&w.data.images?w.data.images.length:0)}});ST.pageStats=st;D.renderWidgets()})};
    D._loadPages=function(uid){FB.onSnapshot(FB.query(FB.collection(FB.db,FB.COL.PAGES),FB.where('userId','==',uid)),function(s){var p=[];s.forEach(function(d){p.push({id:d.id,title:d.data().title})});D.renderPagesList(p)})};

    D.handleSignOut=async function(){var m=await import("https://www.gstatic.com/firebasejs/12.16.0/firebase-auth.js");await m.signOut(FB.auth);window.location.href='sign.html'};

    document.addEventListener('click',function(e){if(!e.target.closest('.widget-menu-btn')&&!e.target.closest('#widgetContextMenu'))D.closeContextMenu();if(!e.target.closest('.dropdown')){var a=D.el('avatarMenu');if(a)a.classList.remove('show')}if(e.target.classList.contains('modal-overlay'))e.target.classList.remove('show')});
    document.addEventListener('keydown',function(e){if(e.key==='Escape'){D.closeContextMenu();D.closeEditPanel();D.closeLightbox();var a=D.el('avatarMenu');if(a)a.classList.remove('show');D.qsa('.modal-overlay.show').forEach(function(m){m.classList.remove('show')});D.closePagesSidebar()}});

    console.log('%c🚀 DockGrid Ready %cby PIReactive','font-size:14px;font-weight:900;color:#ff6b35;font-family:monospace;','font-size:10px;color:#888;');
})();
